// CFDI 4.0 small catalogs (SAT, Anexo 20): the single source for backend validation and
// Invoice Studio (contract §12). Codes are persisted; labels are presentation only.
// `active: false` marks codes recognized by the catalog but not supported in Fase 5.
// Régimen fiscal and Uso CFDI (with its compatibility matrix) are official SAT data;
// the remaining small catalogs are still curated and are migrated in later blocks.
import type {
  CatalogOption,
  InvoiceFiscalCatalogs,
} from "@/types/invoice-studio";

import regimeData from "./sat/catcfdi/c_RegimenFiscal.json";
import cfdiUseData from "./sat/catcfdi/c_UsoCFDI.json";
import catalogManifest from "./sat/catcfdi/manifest.json";

type PersonType = "INDIVIDUAL" | "COMPANY";
type OfficialRegime = {
  code: string;
  description: string;
  personTypes: PersonType[];
  validFrom: string | null;
  validTo: string | null;
};
type OfficialCfdiUse = OfficialRegime & { receiverRegimes: string[] };
const on = (code: string, label: string): CatalogOption => ({
  code,
  label,
  active: true,
});
const off = (code: string, label: string): CatalogOption => ({
  code,
  label,
  active: false,
});

export const documentTypeCatalog = [
  on("I", "Ingreso"),
  off("E", "Egreso"),
  off("T", "Traslado"),
];

export const paymentMethodCatalog = [
  on("PUE", "Pago en una sola exhibición"),
  on("PPD", "Pago en parcialidades o diferido"),
];

export const paymentFormCatalog = [
  on("01", "Efectivo"),
  on("02", "Cheque nominativo"),
  on("03", "Transferencia electrónica de fondos"),
  on("04", "Tarjeta de crédito"),
  on("05", "Monedero electrónico"),
  on("06", "Dinero electrónico"),
  on("08", "Vales de despensa"),
  on("12", "Dación en pago"),
  on("13", "Pago por subrogación"),
  on("14", "Pago por consignación"),
  on("15", "Condonación"),
  on("17", "Compensación"),
  on("23", "Novación"),
  on("24", "Confusión"),
  on("25", "Remisión de deuda"),
  on("26", "Prescripción o caducidad"),
  on("27", "A satisfacción del acreedor"),
  on("28", "Tarjeta de débito"),
  on("29", "Tarjeta de servicios"),
  on("30", "Aplicación de anticipos"),
  on("31", "Intermediario pagos"),
  on("99", "Por definir"),
];

// c_RegimenFiscal and c_UsoCFDI come from the official, versioned catCFDI resources
// (src/lib/sat/catcfdi, generated by scripts/sat/build-catcfdi.mjs). Never edit by hand.
const regimeEntries: OfficialRegime[] = regimeData.entries as OfficialRegime[];
const cfdiUseEntries: OfficialCfdiUse[] =
  cfdiUseData.entries as OfficialCfdiUse[];
const today = () => new Date().toISOString().slice(0, 10);
/** In force on the given ISO date (YYYY-MM-DD) according to the official validity dates. */
export function inForce(
  entry: { validFrom: string | null; validTo: string | null },
  date = today(),
) {
  return (
    (!entry.validFrom || entry.validFrom <= date) &&
    (!entry.validTo || entry.validTo >= date)
  );
}
// Official descriptions end with a period in some catalogs; labels drop it for display.
const label = (description: string) => description.replace(/\.\s*$/, "");

export const officialRegimes = new Map(regimeEntries.map((r) => [r.code, r]));
export const fiscalRegimeCatalog = regimeEntries.map((r) =>
  inForce(r)
    ? on(r.code, label(r.description))
    : off(r.code, label(r.description)),
);
export const regimePersonTypes = new Map(
  regimeEntries.map((r) => [r.code, r.personTypes]),
);

export const officialCfdiUses = new Map(cfdiUseEntries.map((u) => [u.code, u]));
// CP01 (Pagos) and CN01 (Nómina) belong to complements outside Fase 5.
const unsupportedUses = new Set(["CP01", "CN01"]);
export const cfdiUseCatalog = cfdiUseEntries.map((u) =>
  inForce(u) && !unsupportedUses.has(u.code)
    ? on(u.code, label(u.description))
    : off(u.code, label(u.description)),
);
export const cfdiUseRules = new Map(
  cfdiUseEntries.map((u) => [
    u.code,
    { personTypes: u.personTypes, receiverRegimes: u.receiverRegimes },
  ]),
);
/** Version and completeness of the official identity catalogs (contract §7, D5). */
export const identityCatalogSource = {
  release: catalogManifest.release,
  obtainedAt:
    catalogManifest.sources.find((s) => s.name.endsWith(".xls"))?.obtainedAt ??
    null,
  regimesComplete: catalogManifest.catalogs.c_RegimenFiscal.complete,
  cfdiUsesComplete: catalogManifest.catalogs.c_UsoCFDI.complete,
};

export const currencyCatalog = [
  on("MXN", "Peso Mexicano"),
  on("USD", "Dólar americano"),
  on("EUR", "Euro"),
];

export const taxObjectCatalog = [
  on("01", "No objeto de impuesto"),
  on("02", "Sí objeto de impuesto"),
  on("03", "Sí objeto del impuesto y no obligado al desglose"),
  on("04", "Sí objeto del impuesto y no causa impuesto"),
  off("05", "Sí objeto del impuesto, IVA crédito PODEBI"),
  off("06", "Sí objeto del IVA, No traslado IVA"),
  off("07", "No traslado del IVA, Sí desglose IEPS"),
  off("08", "No traslado del IVA, No desglose IEPS"),
];

export const exportCodeCatalog = [
  on("01", "No aplica"),
  off("02", "Definitiva con clave A1"),
  on("03", "Temporal"),
  on(
    "04",
    "Definitiva con clave distinta a A1 o cuando no existe enajenación en términos del CFF",
  ),
];

export const invoiceFiscalCatalogs: InvoiceFiscalCatalogs = {
  documentTypes: documentTypeCatalog,
  paymentMethods: paymentMethodCatalog,
  paymentForms: paymentFormCatalog,
  cfdiUses: cfdiUseCatalog,
  fiscalRegimes: fiscalRegimeCatalog,
  currencies: currencyCatalog,
  taxObjects: taxObjectCatalog,
  exportCodes: exportCodeCatalog,
};

// IVA traslado rates (c_TasaOCuota, TipoFactor Tasa) and withholding upper bounds.
export const vatRates = ["0.16", "0.08", "0"];
/** "0.160000" -> "0.16", "0.0" -> "0"; string-based so rates never pass through floats. */
export function canonicalRate(value: string) {
  return value.includes(".")
    ? value.replace(/0+$/, "").replace(/\.$/, "")
    : value;
}
export const maxWithholdingVatRate = "0.16",
  maxWithholdingIsrRate = "0.35";
export const genericRfc = {
  publicGeneral: "XAXX010101000",
  foreign: "XEXX010101000",
} as const;
export const genericProductCode = "01010101";

const codes = (catalog: CatalogOption[]) => new Set(catalog.map((o) => o.code));
export const catalogCodes = {
  documentType: codes(documentTypeCatalog),
  paymentMethod: codes(paymentMethodCatalog),
  paymentForm: codes(paymentFormCatalog),
  fiscalRegime: codes(fiscalRegimeCatalog),
  cfdiUse: codes(cfdiUseCatalog),
  currency: codes(currencyCatalog),
  taxObject: codes(taxObjectCatalog),
  exportCode: codes(exportCodeCatalog),
};
export function catalogOption(catalog: CatalogOption[], code?: string | null) {
  return code ? catalog.find((o) => o.code === code) : undefined;
}
