// Fase 5C shared contract: stamping attempts and READY → ISSUED
// (docs/tasks/FASE5C-CONTRACT.md §3-4, §17-29). Not server-only: types only.
// InvoiceStatus is unchanged; attempt states live only on StampAttempt.
// ISSUED requires a validated stamped XML from a real PAC; no mock ever yields
// PRODUCTION. No CSD password, private key or PAC credential appears here.
import type { InvoiceStatus } from "./invoice-studio";

/** Persisted separately; SANDBOX is excluded from productive lists and metrics (D8). */
export type PacEnvironment = "SANDBOX" | "PRODUCTION";

/**
 * UNKNOWN means ORBIT cannot prove whether the PAC stamped: it is never retried
 * automatically and never marked FAILED automatically; it must be reconciled first.
 */
export type StampAttemptStatus =
  | "PENDING"
  | "SIGNING"
  | "SUBMITTING"
  | "WAITING_PROVIDER"
  | "SUCCEEDED"
  | "FAILED"
  | "UNKNOWN";

/** Why the "Timbrar CFDI" action is unavailable; the backend is the authority. */
export type StampBlockingReason =
  | "STAMPING_DISABLED"
  | "PAC_NOT_CONFIGURED"
  | "ORGANIZATION_NOT_ENTITLED"
  | "ROLE_NOT_ALLOWED"
  | "CSD_NOT_VALID"
  | "INVOICE_NOT_READY"
  | "DOCUMENT_TYPE_NOT_SUPPORTED"
  | "ATTEMPT_IN_PROGRESS"
  /** A previous attempt is UNKNOWN; reconcile before any new submission. */
  | "RECONCILIATION_REQUIRED"
  | "PRIVACY_NOTICE_MISSING";

/** Per-invoice authorization text (§28), served by the backend with its version. */
export type StampAuthorizationTerms = { version: string; text: string };

export type StampAttemptSummary = {
  id: string;
  status: StampAttemptStatus;
  environment: PacEnvironment;
  /** Provider identifier; never a URL, header or credential. */
  provider: string;
  /** Exact draft version that was signed for this attempt. */
  draftVersion: number;
  startedAt: string;
  submittedAt: string | null;
  completedAt: string | null;
  /** Normalized and sanitized; never raw provider payloads or secrets. */
  error: { code: string; message: string } | null;
  canReconcile: boolean;
};

export type StampedInvoiceState = {
  id: string;
  status: InvoiceStatus;
  version: number;
  /** From the Timbre Fiscal Digital only; never generated by ORBIT. */
  uuid: string | null;
  /** CFDI emission date-time (Comprobante Fecha). */
  issuedAt: string | null;
  /** FechaTimbrado from the Timbre Fiscal Digital; kept separate from issuedAt. */
  stampedAt: string | null;
  fiscalEnvironment: PacEnvironment | null;
  /** Private downloads through the existing GET /api/documents/[id]. */
  xmlDocumentId: string | null;
  pdfDocumentId: string | null;
};

/** GET /api/outgoing-invoices/[id]/stamp (planned). */
export type InvoiceStampingState = {
  availability: {
    enabled: boolean;
    environment: PacEnvironment | null;
    reasons: StampBlockingReason[];
  };
  authorization: StampAuthorizationTerms;
  invoice: StampedInvoiceState;
  latestAttempt: StampAttemptSummary | null;
};

/**
 * POST /api/outgoing-invoices/[id]/stamp (planned, OWNER/ADMIN only).
 * The idempotency key is generated server-side; the browser never sends one.
 * Repeating the same request returns the existing attempt instead of a new stamp.
 */
export type StampRequest = {
  expectedVersion: number;
  /** Checkbox starts unchecked; applies only to this invoice and version. */
  authorization: { accepted: true; version: string };
};

/**
 * Response of POST .../stamp and POST /api/outgoing-invoices/[id]/stamp/reconcile (planned).
 * attempt.status may be SUCCEEDED, FAILED or UNKNOWN; only a validated stamped
 * XML moves the invoice to ISSUED.
 */
export type StampResponse = {
  invoice: StampedInvoiceState;
  attempt: StampAttemptSummary;
};

/**
 * Error codes returned as { error, code, validation? } by the planned stamping routes.
 * POST /api/outgoing-invoices/[id]/pdf (planned) regenerates the PDF and never re-stamps.
 */
export type StampErrorCode =
  | "STAMPING_DISABLED"
  | "STAMPING_NOT_ALLOWED"
  | "VERSION_CONFLICT"
  | "INVOICE_NOT_READY"
  | "NOT_READY"
  | "STAMP_IN_PROGRESS"
  | "RECONCILIATION_REQUIRED"
  | "CSD_NOT_VALID";
